name: amenolink
description: Cliente AmenoLink
version: 0.0.1

environment:
  sdk: ^3.12.2

dependencies:
  http: ^1.6.0
  signalr_core: ^1.1.2
  ulid: ^2.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
