from typing import Protocol, Any, Callable, Generic, TypeVar
from .dtos import Message, TopicMessage, ActionRequest

T = TypeVar('T')
R = TypeVar('R')

type ActionHandler = Callable[..., str]
type CacheAllHandler = Callable[[str, Any], None]
type CacheKeyHandler[T] = Callable[[T | None], None]
type TopicHandler[T] = Callable[[TopicMessage[T]], None]


class Action(Protocol):
    @property
    def name(self) -> str: ...
    def request(self, payload: Any, response_type: type[T]) -> T: ...
    def queue(self, payload: Any) -> None: ...


class CacheWatcher(Protocol):
    @property
    def group(self) -> str: ...
    def all(self, handler: CacheAllHandler) -> None: ...
    def key(self, key: str, handler: Callable[[Any | None], None]) -> None: ...
    def dispose(self) -> None: ...


class Cache(Protocol):
    @property
    def group(self) -> str: ...
    def get(self, key: str, response_type: type[T]) -> T | None: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_or_create(self, key: str, creator: Callable[[], T]) -> T: ...
    def all(self) -> dict[str, Any]: ...
    def clear(self) -> None: ...
    def delete(self, key: str) -> None: ...
    def watch(self) -> CacheWatcher: ...


class Topic(Protocol, Generic[T]):
    @property
    def name(self) -> str: ...
    def subscribe(self, handler: TopicHandler[T]) -> None: ...
    def publish(self, value: T | None = None, previous: Message | None = None) -> None: ...
    def dispose(self) -> None: ...


class ActionContext(Protocol):
    @property
    def request(self) -> ActionRequest: ...
    def log(self, message: str) -> None: ...


class ActionRouter(Protocol):
    def add(self, route: str, handler: ActionHandler) -> None: ...
    def serve(self) -> None: ...


class Connection(Protocol):
    def subscribe(self, listener: Callable[[Any], None]) -> None: ...
    def unsubscribe(self, listener: Callable[[Any], None]) -> None: ...
    def unsubscribe_all(self) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
